// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ryanjdkiyshemacdfzrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ5YW5qZGtpeXNoZW1hY2RmenJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMTIzMTIsImV4cCI6MjA3MTc4ODMxMn0.Hb3Cs7SoUKFfKunaa8ASGHOhEoSDgnEPxJQCskxXQno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});